/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ScreensRouteImport } from './routes/screens'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminAuditLogsRouteImport } from './routes/admin.audit-logs'
import { Route as AdminCommissionsRouteImport } from './routes/admin.commissions'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminDriverCommissionsRouteImport } from './routes/admin.driver-commissions'
import { Route as AdminDriversRouteImport } from './routes/admin.drivers'
import { Route as AdminNotificationsRouteImport } from './routes/admin.notifications'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminPaymentsRouteImport } from './routes/admin.payments'
import { Route as AdminPricingRouteImport } from './routes/admin.pricing'
import { Route as AdminRefundsRouteImport } from './routes/admin.refunds'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminRestaurantsRouteImport } from './routes/admin.restaurants'
import { Route as AdminReviewsRouteImport } from './routes/admin.reviews'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSettlementsRouteImport } from './routes/admin.settlements'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppAddressRouteImport } from './routes/app.address'
import { Route as AppCartRouteImport } from './routes/app.cart'
import { Route as AppCheckoutRouteImport } from './routes/app.checkout'
import { Route as AppFavoritesRouteImport } from './routes/app.favorites'
import { Route as AppNotificationsRouteImport } from './routes/app.notifications'
import { Route as AppOrderPlacedRouteImport } from './routes/app.order-placed'
import { Route as AppOrdersRouteImport } from './routes/app.orders'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppSearchRouteImport } from './routes/app.search'
import { Route as AppWalletRouteImport } from './routes/app.wallet'
import { Route as AuthDriverRouteImport } from './routes/auth.driver'
import { Route as AuthLocationRouteImport } from './routes/auth.location'
import { Route as AuthLoginRouteImport } from './routes/auth.login'
import { Route as AuthOtpRouteImport } from './routes/auth.otp'
import { Route as AuthRegisterRouteImport } from './routes/auth.register'
import { Route as AuthRegisterRestaurantRouteImport } from './routes/auth.register-restaurant'
import { Route as AuthWelcomeRouteImport } from './routes/auth.welcome'
import { Route as BranchIndexRouteImport } from './routes/branch.index'
import { Route as BranchDriversRouteImport } from './routes/branch.drivers'
import { Route as BranchInventoryRouteImport } from './routes/branch.inventory'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as DriverDeliveredRouteImport } from './routes/driver.delivered'
import { Route as DriverDocumentsRouteImport } from './routes/driver.documents'
import { Route as DriverHistoryRouteImport } from './routes/driver.history'
import { Route as DriverNavigateRouteImport } from './routes/driver.navigate'
import { Route as DriverOfferRouteImport } from './routes/driver.offer'
import { Route as DriverProfileRouteImport } from './routes/driver.profile'
import { Route as DriverWalletRouteImport } from './routes/driver.wallet'
import { Route as PartnerIndexRouteImport } from './routes/partner.index'
import { Route as PartnerAnalyticsRouteImport } from './routes/partner.analytics'
import { Route as PartnerBranchesRouteImport } from './routes/partner.branches'
import { Route as PartnerDriversRouteImport } from './routes/partner.drivers'
import { Route as PartnerHoursRouteImport } from './routes/partner.hours'
import { Route as PartnerInventoryRouteImport } from './routes/partner.inventory'
import { Route as PartnerMenuRouteImport } from './routes/partner.menu'
import { Route as PartnerOffersRouteImport } from './routes/partner.offers'
import { Route as PartnerOrdersRouteImport } from './routes/partner.orders'
import { Route as PartnerReviewsRouteImport } from './routes/partner.reviews'
import { Route as PartnerSettingsRouteImport } from './routes/partner.settings'
import { Route as PartnerSettlementsRouteImport } from './routes/partner.settlements'
import { Route as PartnerStaffRouteImport } from './routes/partner.staff'
import { Route as SAddAddressRouteImport } from './routes/s/add-address'
import { Route as SAdminDashboardOverviewMobileRouteImport } from './routes/s/admin-dashboard-overview-mobile'
import { Route as SAdminOrdersManagementMobileRouteImport } from './routes/s/admin-orders-management-mobile'
import { Route as SBusinessTypeSelectionRouteImport } from './routes/s/business-type-selection'
import { Route as SCheckoutRouteImport } from './routes/s/checkout'
import { Route as SDeliveryCompletedRouteImport } from './routes/s/delivery-completed'
import { Route as SDriverEarningsDashboardRouteImport } from './routes/s/driver-earnings-dashboard'
import { Route as SDriverHomeOnlineRouteImport } from './routes/s/driver-home-online'
import { Route as SDriverOperationsMobileRouteImport } from './routes/s/driver-operations-mobile'
import { Route as SFinancePayoutsMobileRouteImport } from './routes/s/finance-payouts-mobile'
import { Route as SHomeDiscoveryRouteImport } from './routes/s/home-discovery'
import { Route as SLocationSelectionRouteImport } from './routes/s/location-selection'
import { Route as SLoginScreenRouteImport } from './routes/s/login-screen'
import { Route as SMerchantAnalyticsRouteImport } from './routes/s/merchant-analytics'
import { Route as SMerchantCatalogRestaurantRouteImport } from './routes/s/merchant-catalog-restaurant'
import { Route as SMerchantDashboardRestaurantRouteImport } from './routes/s/merchant-dashboard-restaurant'
import { Route as SMerchantManagementMobileRouteImport } from './routes/s/merchant-management-mobile'
import { Route as SMerchantOrdersManagementRouteImport } from './routes/s/merchant-orders-management'
import { Route as SMyOrdersRouteImport } from './routes/s/my-orders'
import { Route as SNavigationToCustomerRouteImport } from './routes/s/navigation-to-customer'
import { Route as SNewDeliveryRequestRouteImport } from './routes/s/new-delivery-request'
import { Route as SNewOrderAlertRouteImport } from './routes/s/new-order-alert'
import { Route as SOrderSuccessRouteImport } from './routes/s/order-success'
import { Route as SOrderTrackingRouteImport } from './routes/s/order-tracking'
import { Route as SOtpVerificationRouteImport } from './routes/s/otp-verification'
import { Route as SPharmacyListingRouteImport } from './routes/s/pharmacy-listing'
import { Route as SProductDetailsBurgerRouteImport } from './routes/s/product-details-burger'
import { Route as SProfileRouteImport } from './routes/s/profile'
import { Route as SRestaurantListingRouteImport } from './routes/s/restaurant-listing'
import { Route as SSearchRouteImport } from './routes/s/search'
import { Route as SShoppingCartRouteImport } from './routes/s/shopping-cart'
import { Route as SSignUpScreenRouteImport } from './routes/s/sign-up-screen'
import { Route as SSplashScreenRouteImport } from './routes/s/splash-screen'
import { Route as SStoreDetailsRestaurantRouteImport } from './routes/s/store-details-restaurant'
import { Route as SWelcomeScreenRouteImport } from './routes/s/welcome-screen'
import { Route as AdminDriversIdRouteImport } from './routes/admin.drivers.$id'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'
import { Route as AdminRestaurantsIdRouteImport } from './routes/admin.restaurants.$id'
import { Route as AppCategoryIdRouteImport } from './routes/app.category.$id'
import { Route as AppProductIdRouteImport } from './routes/app.product.$id'
import { Route as AppRateIdRouteImport } from './routes/app.rate.$id'
import { Route as AppRefundIdRouteImport } from './routes/app.refund.$id'
import { Route as AppRestaurantIdRouteImport } from './routes/app.restaurant.$id'
import { Route as AppTrackIdRouteImport } from './routes/app.track.$id'
import { Route as PartnerBranchesIdRouteImport } from './routes/partner.branches.$id'
import { Route as PartnerMenuIdRouteImport } from './routes/partner.menu.$id'
import { Route as PartnerOrdersIdRouteImport } from './routes/partner.orders.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ScreensRoute = ScreensRouteImport.update({
  id: '/screens',
  path: '/screens',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditLogsRoute = AdminAuditLogsRouteImport.update({
  id: '/admin/audit-logs',
  path: '/admin/audit-logs',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommissionsRoute = AdminCommissionsRouteImport.update({
  id: '/admin/commissions',
  path: '/admin/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDriverCommissionsRoute = AdminDriverCommissionsRouteImport.update({
  id: '/admin/driver-commissions',
  path: '/admin/driver-commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/admin/drivers',
  path: '/admin/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentsRoute = AdminPaymentsRouteImport.update({
  id: '/admin/payments',
  path: '/admin/payments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPricingRoute = AdminPricingRouteImport.update({
  id: '/admin/pricing',
  path: '/admin/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRefundsRoute = AdminRefundsRouteImport.update({
  id: '/admin/refunds',
  path: '/admin/refunds',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRestaurantsRoute = AdminRestaurantsRouteImport.update({
  id: '/admin/restaurants',
  path: '/admin/restaurants',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/admin/settings',
  path: '/admin/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSettlementsRoute = AdminSettlementsRouteImport.update({
  id: '/admin/settlements',
  path: '/admin/settlements',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/app/',
  path: '/app/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppAddressRoute = AppAddressRouteImport.update({
  id: '/app/address',
  path: '/app/address',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCartRoute = AppCartRouteImport.update({
  id: '/app/cart',
  path: '/app/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AppCheckoutRoute = AppCheckoutRouteImport.update({
  id: '/app/checkout',
  path: '/app/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AppFavoritesRoute = AppFavoritesRouteImport.update({
  id: '/app/favorites',
  path: '/app/favorites',
  getParentRoute: () => rootRouteImport,
} as any)
const AppNotificationsRoute = AppNotificationsRouteImport.update({
  id: '/app/notifications',
  path: '/app/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrderPlacedRoute = AppOrderPlacedRouteImport.update({
  id: '/app/order-placed',
  path: '/app/order-placed',
  getParentRoute: () => rootRouteImport,
} as any)
const AppOrdersRoute = AppOrdersRouteImport.update({
  id: '/app/orders',
  path: '/app/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/app/profile',
  path: '/app/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/app/search',
  path: '/app/search',
  getParentRoute: () => rootRouteImport,
} as any)
const AppWalletRoute = AppWalletRouteImport.update({
  id: '/app/wallet',
  path: '/app/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthDriverRoute = AuthDriverRouteImport.update({
  id: '/auth/driver',
  path: '/auth/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLocationRoute = AuthLocationRouteImport.update({
  id: '/auth/location',
  path: '/auth/location',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/auth/login',
  path: '/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthOtpRoute = AuthOtpRouteImport.update({
  id: '/auth/otp',
  path: '/auth/otp',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRoute = AuthRegisterRouteImport.update({
  id: '/auth/register',
  path: '/auth/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterRestaurantRoute = AuthRegisterRestaurantRouteImport.update({
  id: '/auth/register-restaurant',
  path: '/auth/register-restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthWelcomeRoute = AuthWelcomeRouteImport.update({
  id: '/auth/welcome',
  path: '/auth/welcome',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchIndexRoute = BranchIndexRouteImport.update({
  id: '/branch/',
  path: '/branch/',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchDriversRoute = BranchDriversRouteImport.update({
  id: '/branch/drivers',
  path: '/branch/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchInventoryRoute = BranchInventoryRouteImport.update({
  id: '/branch/inventory',
  path: '/branch/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/driver/',
  path: '/driver/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverDeliveredRoute = DriverDeliveredRouteImport.update({
  id: '/driver/delivered',
  path: '/driver/delivered',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverDocumentsRoute = DriverDocumentsRouteImport.update({
  id: '/driver/documents',
  path: '/driver/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverHistoryRoute = DriverHistoryRouteImport.update({
  id: '/driver/history',
  path: '/driver/history',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverNavigateRoute = DriverNavigateRouteImport.update({
  id: '/driver/navigate',
  path: '/driver/navigate',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverOfferRoute = DriverOfferRouteImport.update({
  id: '/driver/offer',
  path: '/driver/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverProfileRoute = DriverProfileRouteImport.update({
  id: '/driver/profile',
  path: '/driver/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverWalletRoute = DriverWalletRouteImport.update({
  id: '/driver/wallet',
  path: '/driver/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerIndexRoute = PartnerIndexRouteImport.update({
  id: '/partner/',
  path: '/partner/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerAnalyticsRoute = PartnerAnalyticsRouteImport.update({
  id: '/partner/analytics',
  path: '/partner/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerBranchesRoute = PartnerBranchesRouteImport.update({
  id: '/partner/branches',
  path: '/partner/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerDriversRoute = PartnerDriversRouteImport.update({
  id: '/partner/drivers',
  path: '/partner/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerHoursRoute = PartnerHoursRouteImport.update({
  id: '/partner/hours',
  path: '/partner/hours',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerInventoryRoute = PartnerInventoryRouteImport.update({
  id: '/partner/inventory',
  path: '/partner/inventory',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerMenuRoute = PartnerMenuRouteImport.update({
  id: '/partner/menu',
  path: '/partner/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerOffersRoute = PartnerOffersRouteImport.update({
  id: '/partner/offers',
  path: '/partner/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerOrdersRoute = PartnerOrdersRouteImport.update({
  id: '/partner/orders',
  path: '/partner/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerReviewsRoute = PartnerReviewsRouteImport.update({
  id: '/partner/reviews',
  path: '/partner/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerSettingsRoute = PartnerSettingsRouteImport.update({
  id: '/partner/settings',
  path: '/partner/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerSettlementsRoute = PartnerSettlementsRouteImport.update({
  id: '/partner/settlements',
  path: '/partner/settlements',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerStaffRoute = PartnerStaffRouteImport.update({
  id: '/partner/staff',
  path: '/partner/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const SAddAddressRoute = SAddAddressRouteImport.update({
  id: '/s/add-address',
  path: '/s/add-address',
  getParentRoute: () => rootRouteImport,
} as any)
const SAdminDashboardOverviewMobileRoute =
  SAdminDashboardOverviewMobileRouteImport.update({
    id: '/s/admin-dashboard-overview-mobile',
    path: '/s/admin-dashboard-overview-mobile',
    getParentRoute: () => rootRouteImport,
  } as any)
const SAdminOrdersManagementMobileRoute =
  SAdminOrdersManagementMobileRouteImport.update({
    id: '/s/admin-orders-management-mobile',
    path: '/s/admin-orders-management-mobile',
    getParentRoute: () => rootRouteImport,
  } as any)
const SBusinessTypeSelectionRoute = SBusinessTypeSelectionRouteImport.update({
  id: '/s/business-type-selection',
  path: '/s/business-type-selection',
  getParentRoute: () => rootRouteImport,
} as any)
const SCheckoutRoute = SCheckoutRouteImport.update({
  id: '/s/checkout',
  path: '/s/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const SDeliveryCompletedRoute = SDeliveryCompletedRouteImport.update({
  id: '/s/delivery-completed',
  path: '/s/delivery-completed',
  getParentRoute: () => rootRouteImport,
} as any)
const SDriverEarningsDashboardRoute =
  SDriverEarningsDashboardRouteImport.update({
    id: '/s/driver-earnings-dashboard',
    path: '/s/driver-earnings-dashboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const SDriverHomeOnlineRoute = SDriverHomeOnlineRouteImport.update({
  id: '/s/driver-home-online',
  path: '/s/driver-home-online',
  getParentRoute: () => rootRouteImport,
} as any)
const SDriverOperationsMobileRoute = SDriverOperationsMobileRouteImport.update({
  id: '/s/driver-operations-mobile',
  path: '/s/driver-operations-mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const SFinancePayoutsMobileRoute = SFinancePayoutsMobileRouteImport.update({
  id: '/s/finance-payouts-mobile',
  path: '/s/finance-payouts-mobile',
  getParentRoute: () => rootRouteImport,
} as any)
const SHomeDiscoveryRoute = SHomeDiscoveryRouteImport.update({
  id: '/s/home-discovery',
  path: '/s/home-discovery',
  getParentRoute: () => rootRouteImport,
} as any)
const SLocationSelectionRoute = SLocationSelectionRouteImport.update({
  id: '/s/location-selection',
  path: '/s/location-selection',
  getParentRoute: () => rootRouteImport,
} as any)
const SLoginScreenRoute = SLoginScreenRouteImport.update({
  id: '/s/login-screen',
  path: '/s/login-screen',
  getParentRoute: () => rootRouteImport,
} as any)
const SMerchantAnalyticsRoute = SMerchantAnalyticsRouteImport.update({
  id: '/s/merchant-analytics',
  path: '/s/merchant-analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const SMerchantCatalogRestaurantRoute =
  SMerchantCatalogRestaurantRouteImport.update({
    id: '/s/merchant-catalog-restaurant',
    path: '/s/merchant-catalog-restaurant',
    getParentRoute: () => rootRouteImport,
  } as any)
const SMerchantDashboardRestaurantRoute =
  SMerchantDashboardRestaurantRouteImport.update({
    id: '/s/merchant-dashboard-restaurant',
    path: '/s/merchant-dashboard-restaurant',
    getParentRoute: () => rootRouteImport,
  } as any)
const SMerchantManagementMobileRoute =
  SMerchantManagementMobileRouteImport.update({
    id: '/s/merchant-management-mobile',
    path: '/s/merchant-management-mobile',
    getParentRoute: () => rootRouteImport,
  } as any)
const SMerchantOrdersManagementRoute =
  SMerchantOrdersManagementRouteImport.update({
    id: '/s/merchant-orders-management',
    path: '/s/merchant-orders-management',
    getParentRoute: () => rootRouteImport,
  } as any)
const SMyOrdersRoute = SMyOrdersRouteImport.update({
  id: '/s/my-orders',
  path: '/s/my-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const SNavigationToCustomerRoute = SNavigationToCustomerRouteImport.update({
  id: '/s/navigation-to-customer',
  path: '/s/navigation-to-customer',
  getParentRoute: () => rootRouteImport,
} as any)
const SNewDeliveryRequestRoute = SNewDeliveryRequestRouteImport.update({
  id: '/s/new-delivery-request',
  path: '/s/new-delivery-request',
  getParentRoute: () => rootRouteImport,
} as any)
const SNewOrderAlertRoute = SNewOrderAlertRouteImport.update({
  id: '/s/new-order-alert',
  path: '/s/new-order-alert',
  getParentRoute: () => rootRouteImport,
} as any)
const SOrderSuccessRoute = SOrderSuccessRouteImport.update({
  id: '/s/order-success',
  path: '/s/order-success',
  getParentRoute: () => rootRouteImport,
} as any)
const SOrderTrackingRoute = SOrderTrackingRouteImport.update({
  id: '/s/order-tracking',
  path: '/s/order-tracking',
  getParentRoute: () => rootRouteImport,
} as any)
const SOtpVerificationRoute = SOtpVerificationRouteImport.update({
  id: '/s/otp-verification',
  path: '/s/otp-verification',
  getParentRoute: () => rootRouteImport,
} as any)
const SPharmacyListingRoute = SPharmacyListingRouteImport.update({
  id: '/s/pharmacy-listing',
  path: '/s/pharmacy-listing',
  getParentRoute: () => rootRouteImport,
} as any)
const SProductDetailsBurgerRoute = SProductDetailsBurgerRouteImport.update({
  id: '/s/product-details-burger',
  path: '/s/product-details-burger',
  getParentRoute: () => rootRouteImport,
} as any)
const SProfileRoute = SProfileRouteImport.update({
  id: '/s/profile',
  path: '/s/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SRestaurantListingRoute = SRestaurantListingRouteImport.update({
  id: '/s/restaurant-listing',
  path: '/s/restaurant-listing',
  getParentRoute: () => rootRouteImport,
} as any)
const SSearchRoute = SSearchRouteImport.update({
  id: '/s/search',
  path: '/s/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SShoppingCartRoute = SShoppingCartRouteImport.update({
  id: '/s/shopping-cart',
  path: '/s/shopping-cart',
  getParentRoute: () => rootRouteImport,
} as any)
const SSignUpScreenRoute = SSignUpScreenRouteImport.update({
  id: '/s/sign-up-screen',
  path: '/s/sign-up-screen',
  getParentRoute: () => rootRouteImport,
} as any)
const SSplashScreenRoute = SSplashScreenRouteImport.update({
  id: '/s/splash-screen',
  path: '/s/splash-screen',
  getParentRoute: () => rootRouteImport,
} as any)
const SStoreDetailsRestaurantRoute = SStoreDetailsRestaurantRouteImport.update({
  id: '/s/store-details-restaurant',
  path: '/s/store-details-restaurant',
  getParentRoute: () => rootRouteImport,
} as any)
const SWelcomeScreenRoute = SWelcomeScreenRouteImport.update({
  id: '/s/welcome-screen',
  path: '/s/welcome-screen',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDriversIdRoute = AdminDriversIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminDriversRoute,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminOrdersRoute,
} as any)
const AdminRestaurantsIdRoute = AdminRestaurantsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminRestaurantsRoute,
} as any)
const AppCategoryIdRoute = AppCategoryIdRouteImport.update({
  id: '/app/category/$id',
  path: '/app/category/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProductIdRoute = AppProductIdRouteImport.update({
  id: '/app/product/$id',
  path: '/app/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRateIdRoute = AppRateIdRouteImport.update({
  id: '/app/rate/$id',
  path: '/app/rate/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRefundIdRoute = AppRefundIdRouteImport.update({
  id: '/app/refund/$id',
  path: '/app/refund/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRestaurantIdRoute = AppRestaurantIdRouteImport.update({
  id: '/app/restaurant/$id',
  path: '/app/restaurant/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AppTrackIdRoute = AppTrackIdRouteImport.update({
  id: '/app/track/$id',
  path: '/app/track/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerBranchesIdRoute = PartnerBranchesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PartnerBranchesRoute,
} as any)
const PartnerMenuIdRoute = PartnerMenuIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PartnerMenuRoute,
} as any)
const PartnerOrdersIdRoute = PartnerOrdersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PartnerOrdersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/screens': typeof ScreensRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/driver-commissions': typeof AdminDriverCommissionsRoute
  '/admin/drivers': typeof AdminDriversRouteWithChildren
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/restaurants': typeof AdminRestaurantsRouteWithChildren
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/settlements': typeof AdminSettlementsRoute
  '/app/address': typeof AppAddressRoute
  '/app/cart': typeof AppCartRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/order-placed': typeof AppOrderPlacedRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/profile': typeof AppProfileRoute
  '/app/search': typeof AppSearchRoute
  '/app/wallet': typeof AppWalletRoute
  '/auth/driver': typeof AuthDriverRoute
  '/auth/location': typeof AuthLocationRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/register-restaurant': typeof AuthRegisterRestaurantRoute
  '/auth/welcome': typeof AuthWelcomeRoute
  '/branch/drivers': typeof BranchDriversRoute
  '/branch/inventory': typeof BranchInventoryRoute
  '/driver/delivered': typeof DriverDeliveredRoute
  '/driver/documents': typeof DriverDocumentsRoute
  '/driver/history': typeof DriverHistoryRoute
  '/driver/navigate': typeof DriverNavigateRoute
  '/driver/offer': typeof DriverOfferRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/wallet': typeof DriverWalletRoute
  '/partner/analytics': typeof PartnerAnalyticsRoute
  '/partner/branches': typeof PartnerBranchesRouteWithChildren
  '/partner/drivers': typeof PartnerDriversRoute
  '/partner/hours': typeof PartnerHoursRoute
  '/partner/inventory': typeof PartnerInventoryRoute
  '/partner/menu': typeof PartnerMenuRouteWithChildren
  '/partner/offers': typeof PartnerOffersRoute
  '/partner/orders': typeof PartnerOrdersRouteWithChildren
  '/partner/reviews': typeof PartnerReviewsRoute
  '/partner/settings': typeof PartnerSettingsRoute
  '/partner/settlements': typeof PartnerSettlementsRoute
  '/partner/staff': typeof PartnerStaffRoute
  '/s/add-address': typeof SAddAddressRoute
  '/s/admin-dashboard-overview-mobile': typeof SAdminDashboardOverviewMobileRoute
  '/s/admin-orders-management-mobile': typeof SAdminOrdersManagementMobileRoute
  '/s/business-type-selection': typeof SBusinessTypeSelectionRoute
  '/s/checkout': typeof SCheckoutRoute
  '/s/delivery-completed': typeof SDeliveryCompletedRoute
  '/s/driver-earnings-dashboard': typeof SDriverEarningsDashboardRoute
  '/s/driver-home-online': typeof SDriverHomeOnlineRoute
  '/s/driver-operations-mobile': typeof SDriverOperationsMobileRoute
  '/s/finance-payouts-mobile': typeof SFinancePayoutsMobileRoute
  '/s/home-discovery': typeof SHomeDiscoveryRoute
  '/s/location-selection': typeof SLocationSelectionRoute
  '/s/login-screen': typeof SLoginScreenRoute
  '/s/merchant-analytics': typeof SMerchantAnalyticsRoute
  '/s/merchant-catalog-restaurant': typeof SMerchantCatalogRestaurantRoute
  '/s/merchant-dashboard-restaurant': typeof SMerchantDashboardRestaurantRoute
  '/s/merchant-management-mobile': typeof SMerchantManagementMobileRoute
  '/s/merchant-orders-management': typeof SMerchantOrdersManagementRoute
  '/s/my-orders': typeof SMyOrdersRoute
  '/s/navigation-to-customer': typeof SNavigationToCustomerRoute
  '/s/new-delivery-request': typeof SNewDeliveryRequestRoute
  '/s/new-order-alert': typeof SNewOrderAlertRoute
  '/s/order-success': typeof SOrderSuccessRoute
  '/s/order-tracking': typeof SOrderTrackingRoute
  '/s/otp-verification': typeof SOtpVerificationRoute
  '/s/pharmacy-listing': typeof SPharmacyListingRoute
  '/s/product-details-burger': typeof SProductDetailsBurgerRoute
  '/s/profile': typeof SProfileRoute
  '/s/restaurant-listing': typeof SRestaurantListingRoute
  '/s/search': typeof SSearchRoute
  '/s/shopping-cart': typeof SShoppingCartRoute
  '/s/sign-up-screen': typeof SSignUpScreenRoute
  '/s/splash-screen': typeof SSplashScreenRoute
  '/s/store-details-restaurant': typeof SStoreDetailsRestaurantRoute
  '/s/welcome-screen': typeof SWelcomeScreenRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/branch/': typeof BranchIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/admin/drivers/$id': typeof AdminDriversIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/restaurants/$id': typeof AdminRestaurantsIdRoute
  '/app/category/$id': typeof AppCategoryIdRoute
  '/app/product/$id': typeof AppProductIdRoute
  '/app/rate/$id': typeof AppRateIdRoute
  '/app/refund/$id': typeof AppRefundIdRoute
  '/app/restaurant/$id': typeof AppRestaurantIdRoute
  '/app/track/$id': typeof AppTrackIdRoute
  '/partner/branches/$id': typeof PartnerBranchesIdRoute
  '/partner/menu/$id': typeof PartnerMenuIdRoute
  '/partner/orders/$id': typeof PartnerOrdersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/screens': typeof ScreensRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/driver-commissions': typeof AdminDriverCommissionsRoute
  '/admin/drivers': typeof AdminDriversRouteWithChildren
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/restaurants': typeof AdminRestaurantsRouteWithChildren
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/settlements': typeof AdminSettlementsRoute
  '/app/address': typeof AppAddressRoute
  '/app/cart': typeof AppCartRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/order-placed': typeof AppOrderPlacedRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/profile': typeof AppProfileRoute
  '/app/search': typeof AppSearchRoute
  '/app/wallet': typeof AppWalletRoute
  '/auth/driver': typeof AuthDriverRoute
  '/auth/location': typeof AuthLocationRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/register-restaurant': typeof AuthRegisterRestaurantRoute
  '/auth/welcome': typeof AuthWelcomeRoute
  '/branch/drivers': typeof BranchDriversRoute
  '/branch/inventory': typeof BranchInventoryRoute
  '/driver/delivered': typeof DriverDeliveredRoute
  '/driver/documents': typeof DriverDocumentsRoute
  '/driver/history': typeof DriverHistoryRoute
  '/driver/navigate': typeof DriverNavigateRoute
  '/driver/offer': typeof DriverOfferRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/wallet': typeof DriverWalletRoute
  '/partner/analytics': typeof PartnerAnalyticsRoute
  '/partner/branches': typeof PartnerBranchesRouteWithChildren
  '/partner/drivers': typeof PartnerDriversRoute
  '/partner/hours': typeof PartnerHoursRoute
  '/partner/inventory': typeof PartnerInventoryRoute
  '/partner/menu': typeof PartnerMenuRouteWithChildren
  '/partner/offers': typeof PartnerOffersRoute
  '/partner/orders': typeof PartnerOrdersRouteWithChildren
  '/partner/reviews': typeof PartnerReviewsRoute
  '/partner/settings': typeof PartnerSettingsRoute
  '/partner/settlements': typeof PartnerSettlementsRoute
  '/partner/staff': typeof PartnerStaffRoute
  '/s/add-address': typeof SAddAddressRoute
  '/s/admin-dashboard-overview-mobile': typeof SAdminDashboardOverviewMobileRoute
  '/s/admin-orders-management-mobile': typeof SAdminOrdersManagementMobileRoute
  '/s/business-type-selection': typeof SBusinessTypeSelectionRoute
  '/s/checkout': typeof SCheckoutRoute
  '/s/delivery-completed': typeof SDeliveryCompletedRoute
  '/s/driver-earnings-dashboard': typeof SDriverEarningsDashboardRoute
  '/s/driver-home-online': typeof SDriverHomeOnlineRoute
  '/s/driver-operations-mobile': typeof SDriverOperationsMobileRoute
  '/s/finance-payouts-mobile': typeof SFinancePayoutsMobileRoute
  '/s/home-discovery': typeof SHomeDiscoveryRoute
  '/s/location-selection': typeof SLocationSelectionRoute
  '/s/login-screen': typeof SLoginScreenRoute
  '/s/merchant-analytics': typeof SMerchantAnalyticsRoute
  '/s/merchant-catalog-restaurant': typeof SMerchantCatalogRestaurantRoute
  '/s/merchant-dashboard-restaurant': typeof SMerchantDashboardRestaurantRoute
  '/s/merchant-management-mobile': typeof SMerchantManagementMobileRoute
  '/s/merchant-orders-management': typeof SMerchantOrdersManagementRoute
  '/s/my-orders': typeof SMyOrdersRoute
  '/s/navigation-to-customer': typeof SNavigationToCustomerRoute
  '/s/new-delivery-request': typeof SNewDeliveryRequestRoute
  '/s/new-order-alert': typeof SNewOrderAlertRoute
  '/s/order-success': typeof SOrderSuccessRoute
  '/s/order-tracking': typeof SOrderTrackingRoute
  '/s/otp-verification': typeof SOtpVerificationRoute
  '/s/pharmacy-listing': typeof SPharmacyListingRoute
  '/s/product-details-burger': typeof SProductDetailsBurgerRoute
  '/s/profile': typeof SProfileRoute
  '/s/restaurant-listing': typeof SRestaurantListingRoute
  '/s/search': typeof SSearchRoute
  '/s/shopping-cart': typeof SShoppingCartRoute
  '/s/sign-up-screen': typeof SSignUpScreenRoute
  '/s/splash-screen': typeof SSplashScreenRoute
  '/s/store-details-restaurant': typeof SStoreDetailsRestaurantRoute
  '/s/welcome-screen': typeof SWelcomeScreenRoute
  '/admin': typeof AdminIndexRoute
  '/app': typeof AppIndexRoute
  '/branch': typeof BranchIndexRoute
  '/driver': typeof DriverIndexRoute
  '/partner': typeof PartnerIndexRoute
  '/admin/drivers/$id': typeof AdminDriversIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/restaurants/$id': typeof AdminRestaurantsIdRoute
  '/app/category/$id': typeof AppCategoryIdRoute
  '/app/product/$id': typeof AppProductIdRoute
  '/app/rate/$id': typeof AppRateIdRoute
  '/app/refund/$id': typeof AppRefundIdRoute
  '/app/restaurant/$id': typeof AppRestaurantIdRoute
  '/app/track/$id': typeof AppTrackIdRoute
  '/partner/branches/$id': typeof PartnerBranchesIdRoute
  '/partner/menu/$id': typeof PartnerMenuIdRoute
  '/partner/orders/$id': typeof PartnerOrdersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/screens': typeof ScreensRoute
  '/admin/audit-logs': typeof AdminAuditLogsRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/driver-commissions': typeof AdminDriverCommissionsRoute
  '/admin/drivers': typeof AdminDriversRouteWithChildren
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/orders': typeof AdminOrdersRouteWithChildren
  '/admin/payments': typeof AdminPaymentsRoute
  '/admin/pricing': typeof AdminPricingRoute
  '/admin/refunds': typeof AdminRefundsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/restaurants': typeof AdminRestaurantsRouteWithChildren
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/settlements': typeof AdminSettlementsRoute
  '/app/address': typeof AppAddressRoute
  '/app/cart': typeof AppCartRoute
  '/app/checkout': typeof AppCheckoutRoute
  '/app/favorites': typeof AppFavoritesRoute
  '/app/notifications': typeof AppNotificationsRoute
  '/app/order-placed': typeof AppOrderPlacedRoute
  '/app/orders': typeof AppOrdersRoute
  '/app/profile': typeof AppProfileRoute
  '/app/search': typeof AppSearchRoute
  '/app/wallet': typeof AppWalletRoute
  '/auth/driver': typeof AuthDriverRoute
  '/auth/location': typeof AuthLocationRoute
  '/auth/login': typeof AuthLoginRoute
  '/auth/otp': typeof AuthOtpRoute
  '/auth/register': typeof AuthRegisterRoute
  '/auth/register-restaurant': typeof AuthRegisterRestaurantRoute
  '/auth/welcome': typeof AuthWelcomeRoute
  '/branch/drivers': typeof BranchDriversRoute
  '/branch/inventory': typeof BranchInventoryRoute
  '/driver/delivered': typeof DriverDeliveredRoute
  '/driver/documents': typeof DriverDocumentsRoute
  '/driver/history': typeof DriverHistoryRoute
  '/driver/navigate': typeof DriverNavigateRoute
  '/driver/offer': typeof DriverOfferRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/wallet': typeof DriverWalletRoute
  '/partner/analytics': typeof PartnerAnalyticsRoute
  '/partner/branches': typeof PartnerBranchesRouteWithChildren
  '/partner/drivers': typeof PartnerDriversRoute
  '/partner/hours': typeof PartnerHoursRoute
  '/partner/inventory': typeof PartnerInventoryRoute
  '/partner/menu': typeof PartnerMenuRouteWithChildren
  '/partner/offers': typeof PartnerOffersRoute
  '/partner/orders': typeof PartnerOrdersRouteWithChildren
  '/partner/reviews': typeof PartnerReviewsRoute
  '/partner/settings': typeof PartnerSettingsRoute
  '/partner/settlements': typeof PartnerSettlementsRoute
  '/partner/staff': typeof PartnerStaffRoute
  '/s/add-address': typeof SAddAddressRoute
  '/s/admin-dashboard-overview-mobile': typeof SAdminDashboardOverviewMobileRoute
  '/s/admin-orders-management-mobile': typeof SAdminOrdersManagementMobileRoute
  '/s/business-type-selection': typeof SBusinessTypeSelectionRoute
  '/s/checkout': typeof SCheckoutRoute
  '/s/delivery-completed': typeof SDeliveryCompletedRoute
  '/s/driver-earnings-dashboard': typeof SDriverEarningsDashboardRoute
  '/s/driver-home-online': typeof SDriverHomeOnlineRoute
  '/s/driver-operations-mobile': typeof SDriverOperationsMobileRoute
  '/s/finance-payouts-mobile': typeof SFinancePayoutsMobileRoute
  '/s/home-discovery': typeof SHomeDiscoveryRoute
  '/s/location-selection': typeof SLocationSelectionRoute
  '/s/login-screen': typeof SLoginScreenRoute
  '/s/merchant-analytics': typeof SMerchantAnalyticsRoute
  '/s/merchant-catalog-restaurant': typeof SMerchantCatalogRestaurantRoute
  '/s/merchant-dashboard-restaurant': typeof SMerchantDashboardRestaurantRoute
  '/s/merchant-management-mobile': typeof SMerchantManagementMobileRoute
  '/s/merchant-orders-management': typeof SMerchantOrdersManagementRoute
  '/s/my-orders': typeof SMyOrdersRoute
  '/s/navigation-to-customer': typeof SNavigationToCustomerRoute
  '/s/new-delivery-request': typeof SNewDeliveryRequestRoute
  '/s/new-order-alert': typeof SNewOrderAlertRoute
  '/s/order-success': typeof SOrderSuccessRoute
  '/s/order-tracking': typeof SOrderTrackingRoute
  '/s/otp-verification': typeof SOtpVerificationRoute
  '/s/pharmacy-listing': typeof SPharmacyListingRoute
  '/s/product-details-burger': typeof SProductDetailsBurgerRoute
  '/s/profile': typeof SProfileRoute
  '/s/restaurant-listing': typeof SRestaurantListingRoute
  '/s/search': typeof SSearchRoute
  '/s/shopping-cart': typeof SShoppingCartRoute
  '/s/sign-up-screen': typeof SSignUpScreenRoute
  '/s/splash-screen': typeof SSplashScreenRoute
  '/s/store-details-restaurant': typeof SStoreDetailsRestaurantRoute
  '/s/welcome-screen': typeof SWelcomeScreenRoute
  '/admin/': typeof AdminIndexRoute
  '/app/': typeof AppIndexRoute
  '/branch/': typeof BranchIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/partner/': typeof PartnerIndexRoute
  '/admin/drivers/$id': typeof AdminDriversIdRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/restaurants/$id': typeof AdminRestaurantsIdRoute
  '/app/category/$id': typeof AppCategoryIdRoute
  '/app/product/$id': typeof AppProductIdRoute
  '/app/rate/$id': typeof AppRateIdRoute
  '/app/refund/$id': typeof AppRefundIdRoute
  '/app/restaurant/$id': typeof AppRestaurantIdRoute
  '/app/track/$id': typeof AppTrackIdRoute
  '/partner/branches/$id': typeof PartnerBranchesIdRoute
  '/partner/menu/$id': typeof PartnerMenuIdRoute
  '/partner/orders/$id': typeof PartnerOrdersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/screens'
    | '/admin/audit-logs'
    | '/admin/commissions'
    | '/admin/customers'
    | '/admin/driver-commissions'
    | '/admin/drivers'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/refunds'
    | '/admin/reports'
    | '/admin/restaurants'
    | '/admin/reviews'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/settlements'
    | '/app/address'
    | '/app/cart'
    | '/app/checkout'
    | '/app/favorites'
    | '/app/notifications'
    | '/app/order-placed'
    | '/app/orders'
    | '/app/profile'
    | '/app/search'
    | '/app/wallet'
    | '/auth/driver'
    | '/auth/location'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/auth/register-restaurant'
    | '/auth/welcome'
    | '/branch/drivers'
    | '/branch/inventory'
    | '/driver/delivered'
    | '/driver/documents'
    | '/driver/history'
    | '/driver/navigate'
    | '/driver/offer'
    | '/driver/profile'
    | '/driver/wallet'
    | '/partner/analytics'
    | '/partner/branches'
    | '/partner/drivers'
    | '/partner/hours'
    | '/partner/inventory'
    | '/partner/menu'
    | '/partner/offers'
    | '/partner/orders'
    | '/partner/reviews'
    | '/partner/settings'
    | '/partner/settlements'
    | '/partner/staff'
    | '/s/add-address'
    | '/s/admin-dashboard-overview-mobile'
    | '/s/admin-orders-management-mobile'
    | '/s/business-type-selection'
    | '/s/checkout'
    | '/s/delivery-completed'
    | '/s/driver-earnings-dashboard'
    | '/s/driver-home-online'
    | '/s/driver-operations-mobile'
    | '/s/finance-payouts-mobile'
    | '/s/home-discovery'
    | '/s/location-selection'
    | '/s/login-screen'
    | '/s/merchant-analytics'
    | '/s/merchant-catalog-restaurant'
    | '/s/merchant-dashboard-restaurant'
    | '/s/merchant-management-mobile'
    | '/s/merchant-orders-management'
    | '/s/my-orders'
    | '/s/navigation-to-customer'
    | '/s/new-delivery-request'
    | '/s/new-order-alert'
    | '/s/order-success'
    | '/s/order-tracking'
    | '/s/otp-verification'
    | '/s/pharmacy-listing'
    | '/s/product-details-burger'
    | '/s/profile'
    | '/s/restaurant-listing'
    | '/s/search'
    | '/s/shopping-cart'
    | '/s/sign-up-screen'
    | '/s/splash-screen'
    | '/s/store-details-restaurant'
    | '/s/welcome-screen'
    | '/admin/'
    | '/app/'
    | '/branch/'
    | '/driver/'
    | '/partner/'
    | '/admin/drivers/$id'
    | '/admin/orders/$id'
    | '/admin/restaurants/$id'
    | '/app/category/$id'
    | '/app/product/$id'
    | '/app/rate/$id'
    | '/app/refund/$id'
    | '/app/restaurant/$id'
    | '/app/track/$id'
    | '/partner/branches/$id'
    | '/partner/menu/$id'
    | '/partner/orders/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/screens'
    | '/admin/audit-logs'
    | '/admin/commissions'
    | '/admin/customers'
    | '/admin/driver-commissions'
    | '/admin/drivers'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/refunds'
    | '/admin/reports'
    | '/admin/restaurants'
    | '/admin/reviews'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/settlements'
    | '/app/address'
    | '/app/cart'
    | '/app/checkout'
    | '/app/favorites'
    | '/app/notifications'
    | '/app/order-placed'
    | '/app/orders'
    | '/app/profile'
    | '/app/search'
    | '/app/wallet'
    | '/auth/driver'
    | '/auth/location'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/auth/register-restaurant'
    | '/auth/welcome'
    | '/branch/drivers'
    | '/branch/inventory'
    | '/driver/delivered'
    | '/driver/documents'
    | '/driver/history'
    | '/driver/navigate'
    | '/driver/offer'
    | '/driver/profile'
    | '/driver/wallet'
    | '/partner/analytics'
    | '/partner/branches'
    | '/partner/drivers'
    | '/partner/hours'
    | '/partner/inventory'
    | '/partner/menu'
    | '/partner/offers'
    | '/partner/orders'
    | '/partner/reviews'
    | '/partner/settings'
    | '/partner/settlements'
    | '/partner/staff'
    | '/s/add-address'
    | '/s/admin-dashboard-overview-mobile'
    | '/s/admin-orders-management-mobile'
    | '/s/business-type-selection'
    | '/s/checkout'
    | '/s/delivery-completed'
    | '/s/driver-earnings-dashboard'
    | '/s/driver-home-online'
    | '/s/driver-operations-mobile'
    | '/s/finance-payouts-mobile'
    | '/s/home-discovery'
    | '/s/location-selection'
    | '/s/login-screen'
    | '/s/merchant-analytics'
    | '/s/merchant-catalog-restaurant'
    | '/s/merchant-dashboard-restaurant'
    | '/s/merchant-management-mobile'
    | '/s/merchant-orders-management'
    | '/s/my-orders'
    | '/s/navigation-to-customer'
    | '/s/new-delivery-request'
    | '/s/new-order-alert'
    | '/s/order-success'
    | '/s/order-tracking'
    | '/s/otp-verification'
    | '/s/pharmacy-listing'
    | '/s/product-details-burger'
    | '/s/profile'
    | '/s/restaurant-listing'
    | '/s/search'
    | '/s/shopping-cart'
    | '/s/sign-up-screen'
    | '/s/splash-screen'
    | '/s/store-details-restaurant'
    | '/s/welcome-screen'
    | '/admin'
    | '/app'
    | '/branch'
    | '/driver'
    | '/partner'
    | '/admin/drivers/$id'
    | '/admin/orders/$id'
    | '/admin/restaurants/$id'
    | '/app/category/$id'
    | '/app/product/$id'
    | '/app/rate/$id'
    | '/app/refund/$id'
    | '/app/restaurant/$id'
    | '/app/track/$id'
    | '/partner/branches/$id'
    | '/partner/menu/$id'
    | '/partner/orders/$id'
  id:
    | '__root__'
    | '/'
    | '/screens'
    | '/admin/audit-logs'
    | '/admin/commissions'
    | '/admin/customers'
    | '/admin/driver-commissions'
    | '/admin/drivers'
    | '/admin/notifications'
    | '/admin/orders'
    | '/admin/payments'
    | '/admin/pricing'
    | '/admin/refunds'
    | '/admin/reports'
    | '/admin/restaurants'
    | '/admin/reviews'
    | '/admin/roles'
    | '/admin/settings'
    | '/admin/settlements'
    | '/app/address'
    | '/app/cart'
    | '/app/checkout'
    | '/app/favorites'
    | '/app/notifications'
    | '/app/order-placed'
    | '/app/orders'
    | '/app/profile'
    | '/app/search'
    | '/app/wallet'
    | '/auth/driver'
    | '/auth/location'
    | '/auth/login'
    | '/auth/otp'
    | '/auth/register'
    | '/auth/register-restaurant'
    | '/auth/welcome'
    | '/branch/drivers'
    | '/branch/inventory'
    | '/driver/delivered'
    | '/driver/documents'
    | '/driver/history'
    | '/driver/navigate'
    | '/driver/offer'
    | '/driver/profile'
    | '/driver/wallet'
    | '/partner/analytics'
    | '/partner/branches'
    | '/partner/drivers'
    | '/partner/hours'
    | '/partner/inventory'
    | '/partner/menu'
    | '/partner/offers'
    | '/partner/orders'
    | '/partner/reviews'
    | '/partner/settings'
    | '/partner/settlements'
    | '/partner/staff'
    | '/s/add-address'
    | '/s/admin-dashboard-overview-mobile'
    | '/s/admin-orders-management-mobile'
    | '/s/business-type-selection'
    | '/s/checkout'
    | '/s/delivery-completed'
    | '/s/driver-earnings-dashboard'
    | '/s/driver-home-online'
    | '/s/driver-operations-mobile'
    | '/s/finance-payouts-mobile'
    | '/s/home-discovery'
    | '/s/location-selection'
    | '/s/login-screen'
    | '/s/merchant-analytics'
    | '/s/merchant-catalog-restaurant'
    | '/s/merchant-dashboard-restaurant'
    | '/s/merchant-management-mobile'
    | '/s/merchant-orders-management'
    | '/s/my-orders'
    | '/s/navigation-to-customer'
    | '/s/new-delivery-request'
    | '/s/new-order-alert'
    | '/s/order-success'
    | '/s/order-tracking'
    | '/s/otp-verification'
    | '/s/pharmacy-listing'
    | '/s/product-details-burger'
    | '/s/profile'
    | '/s/restaurant-listing'
    | '/s/search'
    | '/s/shopping-cart'
    | '/s/sign-up-screen'
    | '/s/splash-screen'
    | '/s/store-details-restaurant'
    | '/s/welcome-screen'
    | '/admin/'
    | '/app/'
    | '/branch/'
    | '/driver/'
    | '/partner/'
    | '/admin/drivers/$id'
    | '/admin/orders/$id'
    | '/admin/restaurants/$id'
    | '/app/category/$id'
    | '/app/product/$id'
    | '/app/rate/$id'
    | '/app/refund/$id'
    | '/app/restaurant/$id'
    | '/app/track/$id'
    | '/partner/branches/$id'
    | '/partner/menu/$id'
    | '/partner/orders/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ScreensRoute: typeof ScreensRoute
  AdminAuditLogsRoute: typeof AdminAuditLogsRoute
  AdminCommissionsRoute: typeof AdminCommissionsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDriverCommissionsRoute: typeof AdminDriverCommissionsRoute
  AdminDriversRoute: typeof AdminDriversRouteWithChildren
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminOrdersRoute: typeof AdminOrdersRouteWithChildren
  AdminPaymentsRoute: typeof AdminPaymentsRoute
  AdminPricingRoute: typeof AdminPricingRoute
  AdminRefundsRoute: typeof AdminRefundsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminRestaurantsRoute: typeof AdminRestaurantsRouteWithChildren
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSettlementsRoute: typeof AdminSettlementsRoute
  AppAddressRoute: typeof AppAddressRoute
  AppCartRoute: typeof AppCartRoute
  AppCheckoutRoute: typeof AppCheckoutRoute
  AppFavoritesRoute: typeof AppFavoritesRoute
  AppNotificationsRoute: typeof AppNotificationsRoute
  AppOrderPlacedRoute: typeof AppOrderPlacedRoute
  AppOrdersRoute: typeof AppOrdersRoute
  AppProfileRoute: typeof AppProfileRoute
  AppSearchRoute: typeof AppSearchRoute
  AppWalletRoute: typeof AppWalletRoute
  AuthDriverRoute: typeof AuthDriverRoute
  AuthLocationRoute: typeof AuthLocationRoute
  AuthLoginRoute: typeof AuthLoginRoute
  AuthOtpRoute: typeof AuthOtpRoute
  AuthRegisterRoute: typeof AuthRegisterRoute
  AuthRegisterRestaurantRoute: typeof AuthRegisterRestaurantRoute
  AuthWelcomeRoute: typeof AuthWelcomeRoute
  BranchDriversRoute: typeof BranchDriversRoute
  BranchInventoryRoute: typeof BranchInventoryRoute
  DriverDeliveredRoute: typeof DriverDeliveredRoute
  DriverDocumentsRoute: typeof DriverDocumentsRoute
  DriverHistoryRoute: typeof DriverHistoryRoute
  DriverNavigateRoute: typeof DriverNavigateRoute
  DriverOfferRoute: typeof DriverOfferRoute
  DriverProfileRoute: typeof DriverProfileRoute
  DriverWalletRoute: typeof DriverWalletRoute
  PartnerAnalyticsRoute: typeof PartnerAnalyticsRoute
  PartnerBranchesRoute: typeof PartnerBranchesRouteWithChildren
  PartnerDriversRoute: typeof PartnerDriversRoute
  PartnerHoursRoute: typeof PartnerHoursRoute
  PartnerInventoryRoute: typeof PartnerInventoryRoute
  PartnerMenuRoute: typeof PartnerMenuRouteWithChildren
  PartnerOffersRoute: typeof PartnerOffersRoute
  PartnerOrdersRoute: typeof PartnerOrdersRouteWithChildren
  PartnerReviewsRoute: typeof PartnerReviewsRoute
  PartnerSettingsRoute: typeof PartnerSettingsRoute
  PartnerSettlementsRoute: typeof PartnerSettlementsRoute
  PartnerStaffRoute: typeof PartnerStaffRoute
  SAddAddressRoute: typeof SAddAddressRoute
  SAdminDashboardOverviewMobileRoute: typeof SAdminDashboardOverviewMobileRoute
  SAdminOrdersManagementMobileRoute: typeof SAdminOrdersManagementMobileRoute
  SBusinessTypeSelectionRoute: typeof SBusinessTypeSelectionRoute
  SCheckoutRoute: typeof SCheckoutRoute
  SDeliveryCompletedRoute: typeof SDeliveryCompletedRoute
  SDriverEarningsDashboardRoute: typeof SDriverEarningsDashboardRoute
  SDriverHomeOnlineRoute: typeof SDriverHomeOnlineRoute
  SDriverOperationsMobileRoute: typeof SDriverOperationsMobileRoute
  SFinancePayoutsMobileRoute: typeof SFinancePayoutsMobileRoute
  SHomeDiscoveryRoute: typeof SHomeDiscoveryRoute
  SLocationSelectionRoute: typeof SLocationSelectionRoute
  SLoginScreenRoute: typeof SLoginScreenRoute
  SMerchantAnalyticsRoute: typeof SMerchantAnalyticsRoute
  SMerchantCatalogRestaurantRoute: typeof SMerchantCatalogRestaurantRoute
  SMerchantDashboardRestaurantRoute: typeof SMerchantDashboardRestaurantRoute
  SMerchantManagementMobileRoute: typeof SMerchantManagementMobileRoute
  SMerchantOrdersManagementRoute: typeof SMerchantOrdersManagementRoute
  SMyOrdersRoute: typeof SMyOrdersRoute
  SNavigationToCustomerRoute: typeof SNavigationToCustomerRoute
  SNewDeliveryRequestRoute: typeof SNewDeliveryRequestRoute
  SNewOrderAlertRoute: typeof SNewOrderAlertRoute
  SOrderSuccessRoute: typeof SOrderSuccessRoute
  SOrderTrackingRoute: typeof SOrderTrackingRoute
  SOtpVerificationRoute: typeof SOtpVerificationRoute
  SPharmacyListingRoute: typeof SPharmacyListingRoute
  SProductDetailsBurgerRoute: typeof SProductDetailsBurgerRoute
  SProfileRoute: typeof SProfileRoute
  SRestaurantListingRoute: typeof SRestaurantListingRoute
  SSearchRoute: typeof SSearchRoute
  SShoppingCartRoute: typeof SShoppingCartRoute
  SSignUpScreenRoute: typeof SSignUpScreenRoute
  SSplashScreenRoute: typeof SSplashScreenRoute
  SStoreDetailsRestaurantRoute: typeof SStoreDetailsRestaurantRoute
  SWelcomeScreenRoute: typeof SWelcomeScreenRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AppIndexRoute: typeof AppIndexRoute
  BranchIndexRoute: typeof BranchIndexRoute
  DriverIndexRoute: typeof DriverIndexRoute
  PartnerIndexRoute: typeof PartnerIndexRoute
  AppCategoryIdRoute: typeof AppCategoryIdRoute
  AppProductIdRoute: typeof AppProductIdRoute
  AppRateIdRoute: typeof AppRateIdRoute
  AppRefundIdRoute: typeof AppRefundIdRoute
  AppRestaurantIdRoute: typeof AppRestaurantIdRoute
  AppTrackIdRoute: typeof AppTrackIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/screens': {
      id: '/screens'
      path: '/screens'
      fullPath: '/screens'
      preLoaderRoute: typeof ScreensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit-logs': {
      id: '/admin/audit-logs'
      path: '/admin/audit-logs'
      fullPath: '/admin/audit-logs'
      preLoaderRoute: typeof AdminAuditLogsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/commissions': {
      id: '/admin/commissions'
      path: '/admin/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AdminCommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/driver-commissions': {
      id: '/admin/driver-commissions'
      path: '/admin/driver-commissions'
      fullPath: '/admin/driver-commissions'
      preLoaderRoute: typeof AdminDriverCommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/admin/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payments': {
      id: '/admin/payments'
      path: '/admin/payments'
      fullPath: '/admin/payments'
      preLoaderRoute: typeof AdminPaymentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/pricing': {
      id: '/admin/pricing'
      path: '/admin/pricing'
      fullPath: '/admin/pricing'
      preLoaderRoute: typeof AdminPricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/refunds': {
      id: '/admin/refunds'
      path: '/admin/refunds'
      fullPath: '/admin/refunds'
      preLoaderRoute: typeof AdminRefundsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/restaurants': {
      id: '/admin/restaurants'
      path: '/admin/restaurants'
      fullPath: '/admin/restaurants'
      preLoaderRoute: typeof AdminRestaurantsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/admin/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/settlements': {
      id: '/admin/settlements'
      path: '/admin/settlements'
      fullPath: '/admin/settlements'
      preLoaderRoute: typeof AdminSettlementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/app'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/address': {
      id: '/app/address'
      path: '/app/address'
      fullPath: '/app/address'
      preLoaderRoute: typeof AppAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/cart': {
      id: '/app/cart'
      path: '/app/cart'
      fullPath: '/app/cart'
      preLoaderRoute: typeof AppCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/checkout': {
      id: '/app/checkout'
      path: '/app/checkout'
      fullPath: '/app/checkout'
      preLoaderRoute: typeof AppCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/favorites': {
      id: '/app/favorites'
      path: '/app/favorites'
      fullPath: '/app/favorites'
      preLoaderRoute: typeof AppFavoritesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/notifications': {
      id: '/app/notifications'
      path: '/app/notifications'
      fullPath: '/app/notifications'
      preLoaderRoute: typeof AppNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/order-placed': {
      id: '/app/order-placed'
      path: '/app/order-placed'
      fullPath: '/app/order-placed'
      preLoaderRoute: typeof AppOrderPlacedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/orders': {
      id: '/app/orders'
      path: '/app/orders'
      fullPath: '/app/orders'
      preLoaderRoute: typeof AppOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/app/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/search': {
      id: '/app/search'
      path: '/app/search'
      fullPath: '/app/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/wallet': {
      id: '/app/wallet'
      path: '/app/wallet'
      fullPath: '/app/wallet'
      preLoaderRoute: typeof AppWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/driver': {
      id: '/auth/driver'
      path: '/auth/driver'
      fullPath: '/auth/driver'
      preLoaderRoute: typeof AuthDriverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/location': {
      id: '/auth/location'
      path: '/auth/location'
      fullPath: '/auth/location'
      preLoaderRoute: typeof AuthLocationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login': {
      id: '/auth/login'
      path: '/auth/login'
      fullPath: '/auth/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/otp': {
      id: '/auth/otp'
      path: '/auth/otp'
      fullPath: '/auth/otp'
      preLoaderRoute: typeof AuthOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register': {
      id: '/auth/register'
      path: '/auth/register'
      fullPath: '/auth/register'
      preLoaderRoute: typeof AuthRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register-restaurant': {
      id: '/auth/register-restaurant'
      path: '/auth/register-restaurant'
      fullPath: '/auth/register-restaurant'
      preLoaderRoute: typeof AuthRegisterRestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/welcome': {
      id: '/auth/welcome'
      path: '/auth/welcome'
      fullPath: '/auth/welcome'
      preLoaderRoute: typeof AuthWelcomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch/': {
      id: '/branch/'
      path: '/branch'
      fullPath: '/branch/'
      preLoaderRoute: typeof BranchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch/drivers': {
      id: '/branch/drivers'
      path: '/branch/drivers'
      fullPath: '/branch/drivers'
      preLoaderRoute: typeof BranchDriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branch/inventory': {
      id: '/branch/inventory'
      path: '/branch/inventory'
      fullPath: '/branch/inventory'
      preLoaderRoute: typeof BranchInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/': {
      id: '/driver/'
      path: '/driver'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/delivered': {
      id: '/driver/delivered'
      path: '/driver/delivered'
      fullPath: '/driver/delivered'
      preLoaderRoute: typeof DriverDeliveredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/documents': {
      id: '/driver/documents'
      path: '/driver/documents'
      fullPath: '/driver/documents'
      preLoaderRoute: typeof DriverDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/history': {
      id: '/driver/history'
      path: '/driver/history'
      fullPath: '/driver/history'
      preLoaderRoute: typeof DriverHistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/navigate': {
      id: '/driver/navigate'
      path: '/driver/navigate'
      fullPath: '/driver/navigate'
      preLoaderRoute: typeof DriverNavigateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/offer': {
      id: '/driver/offer'
      path: '/driver/offer'
      fullPath: '/driver/offer'
      preLoaderRoute: typeof DriverOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/profile': {
      id: '/driver/profile'
      path: '/driver/profile'
      fullPath: '/driver/profile'
      preLoaderRoute: typeof DriverProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/wallet': {
      id: '/driver/wallet'
      path: '/driver/wallet'
      fullPath: '/driver/wallet'
      preLoaderRoute: typeof DriverWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/': {
      id: '/partner/'
      path: '/partner'
      fullPath: '/partner/'
      preLoaderRoute: typeof PartnerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/analytics': {
      id: '/partner/analytics'
      path: '/partner/analytics'
      fullPath: '/partner/analytics'
      preLoaderRoute: typeof PartnerAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/branches': {
      id: '/partner/branches'
      path: '/partner/branches'
      fullPath: '/partner/branches'
      preLoaderRoute: typeof PartnerBranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/drivers': {
      id: '/partner/drivers'
      path: '/partner/drivers'
      fullPath: '/partner/drivers'
      preLoaderRoute: typeof PartnerDriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/hours': {
      id: '/partner/hours'
      path: '/partner/hours'
      fullPath: '/partner/hours'
      preLoaderRoute: typeof PartnerHoursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/inventory': {
      id: '/partner/inventory'
      path: '/partner/inventory'
      fullPath: '/partner/inventory'
      preLoaderRoute: typeof PartnerInventoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/menu': {
      id: '/partner/menu'
      path: '/partner/menu'
      fullPath: '/partner/menu'
      preLoaderRoute: typeof PartnerMenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/offers': {
      id: '/partner/offers'
      path: '/partner/offers'
      fullPath: '/partner/offers'
      preLoaderRoute: typeof PartnerOffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/orders': {
      id: '/partner/orders'
      path: '/partner/orders'
      fullPath: '/partner/orders'
      preLoaderRoute: typeof PartnerOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/reviews': {
      id: '/partner/reviews'
      path: '/partner/reviews'
      fullPath: '/partner/reviews'
      preLoaderRoute: typeof PartnerReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/settings': {
      id: '/partner/settings'
      path: '/partner/settings'
      fullPath: '/partner/settings'
      preLoaderRoute: typeof PartnerSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/settlements': {
      id: '/partner/settlements'
      path: '/partner/settlements'
      fullPath: '/partner/settlements'
      preLoaderRoute: typeof PartnerSettlementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/staff': {
      id: '/partner/staff'
      path: '/partner/staff'
      fullPath: '/partner/staff'
      preLoaderRoute: typeof PartnerStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/add-address': {
      id: '/s/add-address'
      path: '/s/add-address'
      fullPath: '/s/add-address'
      preLoaderRoute: typeof SAddAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/admin-dashboard-overview-mobile': {
      id: '/s/admin-dashboard-overview-mobile'
      path: '/s/admin-dashboard-overview-mobile'
      fullPath: '/s/admin-dashboard-overview-mobile'
      preLoaderRoute: typeof SAdminDashboardOverviewMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/admin-orders-management-mobile': {
      id: '/s/admin-orders-management-mobile'
      path: '/s/admin-orders-management-mobile'
      fullPath: '/s/admin-orders-management-mobile'
      preLoaderRoute: typeof SAdminOrdersManagementMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/business-type-selection': {
      id: '/s/business-type-selection'
      path: '/s/business-type-selection'
      fullPath: '/s/business-type-selection'
      preLoaderRoute: typeof SBusinessTypeSelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/checkout': {
      id: '/s/checkout'
      path: '/s/checkout'
      fullPath: '/s/checkout'
      preLoaderRoute: typeof SCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/delivery-completed': {
      id: '/s/delivery-completed'
      path: '/s/delivery-completed'
      fullPath: '/s/delivery-completed'
      preLoaderRoute: typeof SDeliveryCompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/driver-earnings-dashboard': {
      id: '/s/driver-earnings-dashboard'
      path: '/s/driver-earnings-dashboard'
      fullPath: '/s/driver-earnings-dashboard'
      preLoaderRoute: typeof SDriverEarningsDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/driver-home-online': {
      id: '/s/driver-home-online'
      path: '/s/driver-home-online'
      fullPath: '/s/driver-home-online'
      preLoaderRoute: typeof SDriverHomeOnlineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/driver-operations-mobile': {
      id: '/s/driver-operations-mobile'
      path: '/s/driver-operations-mobile'
      fullPath: '/s/driver-operations-mobile'
      preLoaderRoute: typeof SDriverOperationsMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/finance-payouts-mobile': {
      id: '/s/finance-payouts-mobile'
      path: '/s/finance-payouts-mobile'
      fullPath: '/s/finance-payouts-mobile'
      preLoaderRoute: typeof SFinancePayoutsMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/home-discovery': {
      id: '/s/home-discovery'
      path: '/s/home-discovery'
      fullPath: '/s/home-discovery'
      preLoaderRoute: typeof SHomeDiscoveryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/location-selection': {
      id: '/s/location-selection'
      path: '/s/location-selection'
      fullPath: '/s/location-selection'
      preLoaderRoute: typeof SLocationSelectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/login-screen': {
      id: '/s/login-screen'
      path: '/s/login-screen'
      fullPath: '/s/login-screen'
      preLoaderRoute: typeof SLoginScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/merchant-analytics': {
      id: '/s/merchant-analytics'
      path: '/s/merchant-analytics'
      fullPath: '/s/merchant-analytics'
      preLoaderRoute: typeof SMerchantAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/merchant-catalog-restaurant': {
      id: '/s/merchant-catalog-restaurant'
      path: '/s/merchant-catalog-restaurant'
      fullPath: '/s/merchant-catalog-restaurant'
      preLoaderRoute: typeof SMerchantCatalogRestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/merchant-dashboard-restaurant': {
      id: '/s/merchant-dashboard-restaurant'
      path: '/s/merchant-dashboard-restaurant'
      fullPath: '/s/merchant-dashboard-restaurant'
      preLoaderRoute: typeof SMerchantDashboardRestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/merchant-management-mobile': {
      id: '/s/merchant-management-mobile'
      path: '/s/merchant-management-mobile'
      fullPath: '/s/merchant-management-mobile'
      preLoaderRoute: typeof SMerchantManagementMobileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/merchant-orders-management': {
      id: '/s/merchant-orders-management'
      path: '/s/merchant-orders-management'
      fullPath: '/s/merchant-orders-management'
      preLoaderRoute: typeof SMerchantOrdersManagementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/my-orders': {
      id: '/s/my-orders'
      path: '/s/my-orders'
      fullPath: '/s/my-orders'
      preLoaderRoute: typeof SMyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/navigation-to-customer': {
      id: '/s/navigation-to-customer'
      path: '/s/navigation-to-customer'
      fullPath: '/s/navigation-to-customer'
      preLoaderRoute: typeof SNavigationToCustomerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/new-delivery-request': {
      id: '/s/new-delivery-request'
      path: '/s/new-delivery-request'
      fullPath: '/s/new-delivery-request'
      preLoaderRoute: typeof SNewDeliveryRequestRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/new-order-alert': {
      id: '/s/new-order-alert'
      path: '/s/new-order-alert'
      fullPath: '/s/new-order-alert'
      preLoaderRoute: typeof SNewOrderAlertRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/order-success': {
      id: '/s/order-success'
      path: '/s/order-success'
      fullPath: '/s/order-success'
      preLoaderRoute: typeof SOrderSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/order-tracking': {
      id: '/s/order-tracking'
      path: '/s/order-tracking'
      fullPath: '/s/order-tracking'
      preLoaderRoute: typeof SOrderTrackingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/otp-verification': {
      id: '/s/otp-verification'
      path: '/s/otp-verification'
      fullPath: '/s/otp-verification'
      preLoaderRoute: typeof SOtpVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/pharmacy-listing': {
      id: '/s/pharmacy-listing'
      path: '/s/pharmacy-listing'
      fullPath: '/s/pharmacy-listing'
      preLoaderRoute: typeof SPharmacyListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/product-details-burger': {
      id: '/s/product-details-burger'
      path: '/s/product-details-burger'
      fullPath: '/s/product-details-burger'
      preLoaderRoute: typeof SProductDetailsBurgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/profile': {
      id: '/s/profile'
      path: '/s/profile'
      fullPath: '/s/profile'
      preLoaderRoute: typeof SProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/restaurant-listing': {
      id: '/s/restaurant-listing'
      path: '/s/restaurant-listing'
      fullPath: '/s/restaurant-listing'
      preLoaderRoute: typeof SRestaurantListingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/search': {
      id: '/s/search'
      path: '/s/search'
      fullPath: '/s/search'
      preLoaderRoute: typeof SSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/shopping-cart': {
      id: '/s/shopping-cart'
      path: '/s/shopping-cart'
      fullPath: '/s/shopping-cart'
      preLoaderRoute: typeof SShoppingCartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/sign-up-screen': {
      id: '/s/sign-up-screen'
      path: '/s/sign-up-screen'
      fullPath: '/s/sign-up-screen'
      preLoaderRoute: typeof SSignUpScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/splash-screen': {
      id: '/s/splash-screen'
      path: '/s/splash-screen'
      fullPath: '/s/splash-screen'
      preLoaderRoute: typeof SSplashScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/store-details-restaurant': {
      id: '/s/store-details-restaurant'
      path: '/s/store-details-restaurant'
      fullPath: '/s/store-details-restaurant'
      preLoaderRoute: typeof SStoreDetailsRestaurantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/s/welcome-screen': {
      id: '/s/welcome-screen'
      path: '/s/welcome-screen'
      fullPath: '/s/welcome-screen'
      preLoaderRoute: typeof SWelcomeScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/drivers/$id': {
      id: '/admin/drivers/$id'
      path: '/$id'
      fullPath: '/admin/drivers/$id'
      preLoaderRoute: typeof AdminDriversIdRouteImport
      parentRoute: typeof AdminDriversRoute
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof AdminOrdersRoute
    }
    '/admin/restaurants/$id': {
      id: '/admin/restaurants/$id'
      path: '/$id'
      fullPath: '/admin/restaurants/$id'
      preLoaderRoute: typeof AdminRestaurantsIdRouteImport
      parentRoute: typeof AdminRestaurantsRoute
    }
    '/app/category/$id': {
      id: '/app/category/$id'
      path: '/app/category/$id'
      fullPath: '/app/category/$id'
      preLoaderRoute: typeof AppCategoryIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/product/$id': {
      id: '/app/product/$id'
      path: '/app/product/$id'
      fullPath: '/app/product/$id'
      preLoaderRoute: typeof AppProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/rate/$id': {
      id: '/app/rate/$id'
      path: '/app/rate/$id'
      fullPath: '/app/rate/$id'
      preLoaderRoute: typeof AppRateIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/refund/$id': {
      id: '/app/refund/$id'
      path: '/app/refund/$id'
      fullPath: '/app/refund/$id'
      preLoaderRoute: typeof AppRefundIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/restaurant/$id': {
      id: '/app/restaurant/$id'
      path: '/app/restaurant/$id'
      fullPath: '/app/restaurant/$id'
      preLoaderRoute: typeof AppRestaurantIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/track/$id': {
      id: '/app/track/$id'
      path: '/app/track/$id'
      fullPath: '/app/track/$id'
      preLoaderRoute: typeof AppTrackIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner/branches/$id': {
      id: '/partner/branches/$id'
      path: '/$id'
      fullPath: '/partner/branches/$id'
      preLoaderRoute: typeof PartnerBranchesIdRouteImport
      parentRoute: typeof PartnerBranchesRoute
    }
    '/partner/menu/$id': {
      id: '/partner/menu/$id'
      path: '/$id'
      fullPath: '/partner/menu/$id'
      preLoaderRoute: typeof PartnerMenuIdRouteImport
      parentRoute: typeof PartnerMenuRoute
    }
    '/partner/orders/$id': {
      id: '/partner/orders/$id'
      path: '/$id'
      fullPath: '/partner/orders/$id'
      preLoaderRoute: typeof PartnerOrdersIdRouteImport
      parentRoute: typeof PartnerOrdersRoute
    }
  }
}

interface AdminDriversRouteChildren {
  AdminDriversIdRoute: typeof AdminDriversIdRoute
}

const AdminDriversRouteChildren: AdminDriversRouteChildren = {
  AdminDriversIdRoute: AdminDriversIdRoute,
}

const AdminDriversRouteWithChildren = AdminDriversRoute._addFileChildren(
  AdminDriversRouteChildren,
)

interface AdminOrdersRouteChildren {
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
}

const AdminOrdersRouteChildren: AdminOrdersRouteChildren = {
  AdminOrdersIdRoute: AdminOrdersIdRoute,
}

const AdminOrdersRouteWithChildren = AdminOrdersRoute._addFileChildren(
  AdminOrdersRouteChildren,
)

interface AdminRestaurantsRouteChildren {
  AdminRestaurantsIdRoute: typeof AdminRestaurantsIdRoute
}

const AdminRestaurantsRouteChildren: AdminRestaurantsRouteChildren = {
  AdminRestaurantsIdRoute: AdminRestaurantsIdRoute,
}

const AdminRestaurantsRouteWithChildren =
  AdminRestaurantsRoute._addFileChildren(AdminRestaurantsRouteChildren)

interface PartnerBranchesRouteChildren {
  PartnerBranchesIdRoute: typeof PartnerBranchesIdRoute
}

const PartnerBranchesRouteChildren: PartnerBranchesRouteChildren = {
  PartnerBranchesIdRoute: PartnerBranchesIdRoute,
}

const PartnerBranchesRouteWithChildren = PartnerBranchesRoute._addFileChildren(
  PartnerBranchesRouteChildren,
)

interface PartnerMenuRouteChildren {
  PartnerMenuIdRoute: typeof PartnerMenuIdRoute
}

const PartnerMenuRouteChildren: PartnerMenuRouteChildren = {
  PartnerMenuIdRoute: PartnerMenuIdRoute,
}

const PartnerMenuRouteWithChildren = PartnerMenuRoute._addFileChildren(
  PartnerMenuRouteChildren,
)

interface PartnerOrdersRouteChildren {
  PartnerOrdersIdRoute: typeof PartnerOrdersIdRoute
}

const PartnerOrdersRouteChildren: PartnerOrdersRouteChildren = {
  PartnerOrdersIdRoute: PartnerOrdersIdRoute,
}

const PartnerOrdersRouteWithChildren = PartnerOrdersRoute._addFileChildren(
  PartnerOrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ScreensRoute: ScreensRoute,
  AdminAuditLogsRoute: AdminAuditLogsRoute,
  AdminCommissionsRoute: AdminCommissionsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDriverCommissionsRoute: AdminDriverCommissionsRoute,
  AdminDriversRoute: AdminDriversRouteWithChildren,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminOrdersRoute: AdminOrdersRouteWithChildren,
  AdminPaymentsRoute: AdminPaymentsRoute,
  AdminPricingRoute: AdminPricingRoute,
  AdminRefundsRoute: AdminRefundsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminRestaurantsRoute: AdminRestaurantsRouteWithChildren,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSettlementsRoute: AdminSettlementsRoute,
  AppAddressRoute: AppAddressRoute,
  AppCartRoute: AppCartRoute,
  AppCheckoutRoute: AppCheckoutRoute,
  AppFavoritesRoute: AppFavoritesRoute,
  AppNotificationsRoute: AppNotificationsRoute,
  AppOrderPlacedRoute: AppOrderPlacedRoute,
  AppOrdersRoute: AppOrdersRoute,
  AppProfileRoute: AppProfileRoute,
  AppSearchRoute: AppSearchRoute,
  AppWalletRoute: AppWalletRoute,
  AuthDriverRoute: AuthDriverRoute,
  AuthLocationRoute: AuthLocationRoute,
  AuthLoginRoute: AuthLoginRoute,
  AuthOtpRoute: AuthOtpRoute,
  AuthRegisterRoute: AuthRegisterRoute,
  AuthRegisterRestaurantRoute: AuthRegisterRestaurantRoute,
  AuthWelcomeRoute: AuthWelcomeRoute,
  BranchDriversRoute: BranchDriversRoute,
  BranchInventoryRoute: BranchInventoryRoute,
  DriverDeliveredRoute: DriverDeliveredRoute,
  DriverDocumentsRoute: DriverDocumentsRoute,
  DriverHistoryRoute: DriverHistoryRoute,
  DriverNavigateRoute: DriverNavigateRoute,
  DriverOfferRoute: DriverOfferRoute,
  DriverProfileRoute: DriverProfileRoute,
  DriverWalletRoute: DriverWalletRoute,
  PartnerAnalyticsRoute: PartnerAnalyticsRoute,
  PartnerBranchesRoute: PartnerBranchesRouteWithChildren,
  PartnerDriversRoute: PartnerDriversRoute,
  PartnerHoursRoute: PartnerHoursRoute,
  PartnerInventoryRoute: PartnerInventoryRoute,
  PartnerMenuRoute: PartnerMenuRouteWithChildren,
  PartnerOffersRoute: PartnerOffersRoute,
  PartnerOrdersRoute: PartnerOrdersRouteWithChildren,
  PartnerReviewsRoute: PartnerReviewsRoute,
  PartnerSettingsRoute: PartnerSettingsRoute,
  PartnerSettlementsRoute: PartnerSettlementsRoute,
  PartnerStaffRoute: PartnerStaffRoute,
  SAddAddressRoute: SAddAddressRoute,
  SAdminDashboardOverviewMobileRoute: SAdminDashboardOverviewMobileRoute,
  SAdminOrdersManagementMobileRoute: SAdminOrdersManagementMobileRoute,
  SBusinessTypeSelectionRoute: SBusinessTypeSelectionRoute,
  SCheckoutRoute: SCheckoutRoute,
  SDeliveryCompletedRoute: SDeliveryCompletedRoute,
  SDriverEarningsDashboardRoute: SDriverEarningsDashboardRoute,
  SDriverHomeOnlineRoute: SDriverHomeOnlineRoute,
  SDriverOperationsMobileRoute: SDriverOperationsMobileRoute,
  SFinancePayoutsMobileRoute: SFinancePayoutsMobileRoute,
  SHomeDiscoveryRoute: SHomeDiscoveryRoute,
  SLocationSelectionRoute: SLocationSelectionRoute,
  SLoginScreenRoute: SLoginScreenRoute,
  SMerchantAnalyticsRoute: SMerchantAnalyticsRoute,
  SMerchantCatalogRestaurantRoute: SMerchantCatalogRestaurantRoute,
  SMerchantDashboardRestaurantRoute: SMerchantDashboardRestaurantRoute,
  SMerchantManagementMobileRoute: SMerchantManagementMobileRoute,
  SMerchantOrdersManagementRoute: SMerchantOrdersManagementRoute,
  SMyOrdersRoute: SMyOrdersRoute,
  SNavigationToCustomerRoute: SNavigationToCustomerRoute,
  SNewDeliveryRequestRoute: SNewDeliveryRequestRoute,
  SNewOrderAlertRoute: SNewOrderAlertRoute,
  SOrderSuccessRoute: SOrderSuccessRoute,
  SOrderTrackingRoute: SOrderTrackingRoute,
  SOtpVerificationRoute: SOtpVerificationRoute,
  SPharmacyListingRoute: SPharmacyListingRoute,
  SProductDetailsBurgerRoute: SProductDetailsBurgerRoute,
  SProfileRoute: SProfileRoute,
  SRestaurantListingRoute: SRestaurantListingRoute,
  SSearchRoute: SSearchRoute,
  SShoppingCartRoute: SShoppingCartRoute,
  SSignUpScreenRoute: SSignUpScreenRoute,
  SSplashScreenRoute: SSplashScreenRoute,
  SStoreDetailsRestaurantRoute: SStoreDetailsRestaurantRoute,
  SWelcomeScreenRoute: SWelcomeScreenRoute,
  AdminIndexRoute: AdminIndexRoute,
  AppIndexRoute: AppIndexRoute,
  BranchIndexRoute: BranchIndexRoute,
  DriverIndexRoute: DriverIndexRoute,
  PartnerIndexRoute: PartnerIndexRoute,
  AppCategoryIdRoute: AppCategoryIdRoute,
  AppProductIdRoute: AppProductIdRoute,
  AppRateIdRoute: AppRateIdRoute,
  AppRefundIdRoute: AppRefundIdRoute,
  AppRestaurantIdRoute: AppRestaurantIdRoute,
  AppTrackIdRoute: AppTrackIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
