import { Router, type IRouter } from "express";
import healthRouter from "./health";
import authRouter from "./auth";
import onboardRouter from "./onboard";
import storageRouter from "./storage";
import menuRouter from "./menu";
import branchesRouter from "./branches";
import restaurantRouter from "./restaurant";
import customerRouter from "./customer";
import cartRouter from "./cart";
import ordersRouter from "./orders";
import paymentsRouter from "./payments";
import driverOrdersRouter from "./driver-orders";
import customerWalletRouter from "./customer-wallet";
import adminRefundsRouter from "./admin-refunds";
import adminCoreRouter from "./admin-core";
import adminAccessRouter from "./admin-access";
import adminOperationsRouter from "./admin-operations";
import partnerOperationsRouter from "./partner-operations";
import driverAccountRouter from "./driver-account";
import notificationDevicesRouter from "./notification-devices";
import manualPayoutsRouter from "./manual-payouts";

const router: IRouter = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(onboardRouter);
router.use(storageRouter);
router.use(menuRouter);
router.use(branchesRouter);
router.use(restaurantRouter);
router.use(customerRouter);
router.use(cartRouter);
router.use(ordersRouter);
router.use(paymentsRouter);
router.use(driverOrdersRouter);
router.use(customerWalletRouter);
router.use(adminRefundsRouter);
router.use(adminCoreRouter);
router.use(adminAccessRouter);
router.use(adminOperationsRouter);
router.use(partnerOperationsRouter);
router.use(driverAccountRouter);
router.use(notificationDevicesRouter);
router.use(manualPayoutsRouter);

export default router;
