// Zod request/response validators (generated by orval from OpenAPI paths)
export * from "./generated/api";

// TypeScript interfaces for schema objects that are NOT already exported as Zod
// validators above. UploadFileResponse is intentionally omitted here to avoid
// the duplicate-export ambiguity — the Zod export from generated/api carries
// the same type information via z.infer.
export type { AuthSession } from "./generated/types/authSession";
export type { AuthUser } from "./generated/types/authUser";
export type { DriverApplication } from "./generated/types/driverApplication";
export type { DriverOnboard } from "./generated/types/driverOnboard";
export type { ErrorResponse } from "./generated/types/errorResponse";
export type { HealthStatus } from "./generated/types/healthStatus";
export type { LocationSaveResult } from "./generated/types/locationSaveResult";
export type { LocationUpdate } from "./generated/types/locationUpdate";
export type { OnboardResult } from "./generated/types/onboardResult";
export type { OtpRequest } from "./generated/types/otpRequest";
export type { OtpRequestResponse } from "./generated/types/otpRequestResponse";
export type { OtpRequestRole } from "./generated/types/otpRequestRole";
export type { OtpVerify } from "./generated/types/otpVerify";
export type { OtpVerifyRole } from "./generated/types/otpVerifyRole";
export type { OtpVerifyType } from "./generated/types/otpVerifyType";
export type { PartnerOnboard } from "./generated/types/partnerOnboard";
export type { PartnerOnboardDeliveryType } from "./generated/types/partnerOnboardDeliveryType";
export type { RestaurantApplication } from "./generated/types/restaurantApplication";
